import React, { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Main from "/public/images/main.png"
import Scroll from "/public/images/scroll.png"
import Fade from 'react-reveal/Fade';
import Bounce  from 'react-reveal/Bounce';


export default function Home() {
  const [isScrolled, setIsScrolled] = useState(false);
  const handleScroll = (event) => {
    if (window.scrollY > 0) {
      setIsScrolled(false);
    } else {
      setIsScrolled(true);
    }
  };
  useEffect(() => {
    window.addEventListener("scroll", handleScroll);
  }, []);

  return (


    <>
      <Head>
        <title>ZOCHIL IO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&family=Roboto&display=swap" rel="stylesheet" />

      </Head>
      <main>
        <div className="h-full  bg-[#1E1E1E] lg:flex grid m-auto relative mt-[68px] ">
          <Fade left>
            <div className="w-[50%] grid place-items-center mb-20 ">
              <div>
                <div className="text-[64px] text-[700] text-[white] leading-[70px] font-primary-font">
                  <b>
                    LAUNCH YOUR <br /> ONLINE BUSINESS
                  </b>
                </div>
                <div className="text-[24px] text-[white] font-primary-font">
                  You can manage your online business by yourself
                </div>
                <p className="text-[#7647EA] text-[48px] text-bold font-primary-font">
                  <b>
                    UNDER 1 MINUTE
                  </b>
                </p>
              </div>
            </div>
          </Fade>
          <Bounce right>
            <div className="w-[50%]">
              <Image src={Main} className="w-[769px] h-[763px] ml-11 mt-[290px]" alt="" />
            </div>
          </Bounce>
          {isScrolled ?
            <div className="scroll__button font-primary-font">
              <p className="mb-2">SCROLL DOWN</p>
              <Image className="hover:scale-125" src={Scroll} alt="" />
            </div>
            : ""
          }
        </div>


      </main>
    </>
  );
}
